### ISSUE TITLE
Remove the devterm-fan-temp-daemon-rpi package from the R01 build

### ISSUE THREAD

**Issue by andypiper** [clockworkpi/DevTerm#38]
Edit https://github.com/clockworkpi/DevTerm/wiki/Create-DevTerm-R01-OS-image-from-scratch#install-devterm-related-package

Remove devterm-fan-temp-daemon-rpi
This package is specific to the Raspberry Pi and will not work on the R01 core.

**Comment by cuu** [comment]
done
