### ISSUE TITLE
Would this module work in a DevTerm? 

### ISSUE THREAD

**Issue by rog77** [clockworkpi/DevTerm#39]
https://github.com/wuxx/icesugar-pro

Not sure of the connector compatability... 

The idea would be to use something like Litex to generate SoC with appropriate peripheral controllers.

Sorry if this is off topic, or out of scope.

**Comment by cuu** [comment]
One thing I can confirm is this board can be plugged into DT
But I am not sure it can run under DT 
if all the GPIO is like as same as CM3, then there is a good chance that it will work

**Comment by rog77** [comment]
https://github.com/wuxx/Colorlight-FPGA-Projects#ddr2-sodimm-200p

I compared the CM pinout to the above, and alas it it not the same. Thanks for your response - it seemed like an idea, but it looks like it is not to be.
