### ISSUE TITLE
"hacked keyboard firmware" commits

### ISSUE THREAD

**Issue by andypiper** [clockworkpi/DevTerm#41]
What are these for please?

[add hacked keyboard stm32duino bootloader files](https://github.com/clockworkpi/DevTerm/commit/548957a344f35e199661954fc35074390f7249e8)

@[cuu](https://github.com/clockworkpi/DevTerm/commits?author=cuu)
cuu committed 2 days ago
 
[add hacked keyboard firmware](https://github.com/clockworkpi/DevTerm/commit/7f8165ee80e9af1f8510fe340b2c64286d842dee)

**Comment by cuu** [comment]
https://forum.clockworkpi.com/t/keyboard-stuck-in-bootloader-mode/8830/16
